[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# Which actions to run on pull requests
pr-run-mode = "upload"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "$HOME/.local/bin"
# Whether to install an updater program
install-updater = false
# Generate changelogs using git-cliff
generate-changelog = true
# Use git-cliff for changelog generation
changelog-backend = "git-cliff"
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
